[project]
name = "kabosu-core"
version = "0.2.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jaconv>=0.4.0",
    "jpreprocess>=0.1.5",
    "kanalizer>=0.1.1",
    "marine-plus>=0.0.6.post3",
    "numpy==1.26.4",
    "onnxruntime>=1.22.1",
    "sudachidict-core>=20250825",
    "sudachipy>=0.6.10",
    "yomikata",
]

[dependency-groups]
dev = [
    "taskipy>=1.14.1",
    "pytest"
]



[tool.hatch.build.targets.sdist]
only-include = [
    "src/kabosu_core",
    "LICENSE",
    "pyproject.toml",
    "README.md",
]
[tool.hatch.build.targets.wheel]
packages = ["src/kabosu_core"]

[tool.uv.sources]
yomikata = { git = "https://github.com/q9uri/yomikata", rev = "e0d23496dd17b1b97a2a91bef08a41f77d3932d8" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
